/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as FlowchartsRouteImport } from './routes/flowcharts'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as InstallRouteImport } from './routes/install'
import { Route as KardexRouteImport } from './routes/kardex'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as VideosRouteImport } from './routes/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowchartsRoute = FlowchartsRouteImport.update({
  id: '/flowcharts',
  path: '/flowcharts',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const KardexRoute = KardexRouteImport.update({
  id: '/kardex',
  path: '/kardex',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attendance': typeof AttendanceRoute
  '/conferences': typeof ConferencesRoute
  '/flowcharts': typeof FlowchartsRoute
  '/incidents': typeof IncidentsRoute
  '/install': typeof InstallRoute
  '/kardex': typeof KardexRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attendance': typeof AttendanceRoute
  '/conferences': typeof ConferencesRoute
  '/flowcharts': typeof FlowchartsRoute
  '/incidents': typeof IncidentsRoute
  '/install': typeof InstallRoute
  '/kardex': typeof KardexRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attendance': typeof AttendanceRoute
  '/conferences': typeof ConferencesRoute
  '/flowcharts': typeof FlowchartsRoute
  '/incidents': typeof IncidentsRoute
  '/install': typeof InstallRoute
  '/kardex': typeof KardexRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/policies': typeof PoliciesRoute
  '/reports': typeof ReportsRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attendance'
    | '/conferences'
    | '/flowcharts'
    | '/incidents'
    | '/install'
    | '/kardex'
    | '/meetings'
    | '/onboarding'
    | '/policies'
    | '/reports'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/attendance'
    | '/conferences'
    | '/flowcharts'
    | '/incidents'
    | '/install'
    | '/kardex'
    | '/meetings'
    | '/onboarding'
    | '/policies'
    | '/reports'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/attendance'
    | '/conferences'
    | '/flowcharts'
    | '/incidents'
    | '/install'
    | '/kardex'
    | '/meetings'
    | '/onboarding'
    | '/policies'
    | '/reports'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AttendanceRoute: typeof AttendanceRoute
  ConferencesRoute: typeof ConferencesRoute
  FlowchartsRoute: typeof FlowchartsRoute
  IncidentsRoute: typeof IncidentsRoute
  InstallRoute: typeof InstallRoute
  KardexRoute: typeof KardexRoute
  MeetingsRoute: typeof MeetingsRoute
  OnboardingRoute: typeof OnboardingRoute
  PoliciesRoute: typeof PoliciesRoute
  ReportsRoute: typeof ReportsRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowcharts': {
      id: '/flowcharts'
      path: '/flowcharts'
      fullPath: '/flowcharts'
      preLoaderRoute: typeof FlowchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kardex': {
      id: '/kardex'
      path: '/kardex'
      fullPath: '/kardex'
      preLoaderRoute: typeof KardexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AttendanceRoute: AttendanceRoute,
  ConferencesRoute: ConferencesRoute,
  FlowchartsRoute: FlowchartsRoute,
  IncidentsRoute: IncidentsRoute,
  InstallRoute: InstallRoute,
  KardexRoute: KardexRoute,
  MeetingsRoute: MeetingsRoute,
  OnboardingRoute: OnboardingRoute,
  PoliciesRoute: PoliciesRoute,
  ReportsRoute: ReportsRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
